#!/usr/bin/env python3

import argparse
import sys
from tempfile import mkstemp


class StderrParser(argparse.ArgumentParser):
    def __init__(self, **kwargs):
        super().__init__(prog='', **kwargs)

    def exit(self, status=0, message=None):
        if message:
            print(message, file=sys.stderr)
        exit(status)

    def error(self, message):
        self.print_usage(file=sys.stderr)
        self.exit(status=1, message=f"ERROR: {message}")


def make_parser(*args):
    parser = StderrParser()
    for arg in args:
        required = False
        if arg.endswith('!'):
            required = True
            arg = arg[:-1]
        if arg.endswith('-'):
            parser.add_argument(f"--{arg[:-1]}", required=required, action='store_true')
        else:
            parser.add_argument(f"--{arg}", required=required)
    return parser


def write_args(options):
    tmpfile = mkstemp(text=True)[1]
    with open(tmpfile, 'w') as dest:
        for var in options_names:
            if var.endswith('-') or var.endswith('!'):
                var = var[:-1]
            if hasattr(options, var):
                val = getattr(options, var)
                if val:
                    dest.write(f"{var}={val}\n")
    return tmpfile


if __name__ == '__main__':
    try:
        pos = sys.argv.index('--')
        options_names = sys.argv[1:pos]
        parser = make_parser(*options_names)
        config = parser.parse_args(sys.argv[pos+1:])
        print(write_args(config))
    except ValueError:
        print(f"Command line is malformed, missing '--' separator", file=sys.stderr)
        exit(1)
