#!/usr/bin/env bash
#
# Example script for the `parse-args` script
#
# Usage: parse_example [-h] [--keep] [--take TAKE] --counts COUNTS [--mount MOUNT]
#
# Use `./parse_example -h` to get a full description of the available CLI args that
# this command makes available to the script.

# This prevents `source` to be invoked at all (and most likely error out)
# when parse-args fails to parse the given arguments.
set -e

# The `-` indicates a bool flag (its presence will set the associated variable, no
# value expected); the `!` indicates a required argument.
PARSED=$(parse-args keep- take counts! mount -- $@)
source ${PARSED}

# For example:
#
#   $ ./parse_example --keep --take 3 --counts 5 --mount /dev/fpo
#   Keeping mount: /dev/fpo
#   Take 3, counts: 5

# Here we are using the parsed arguments as ordinary bash variables.
if [[ -n ${keep} ]]; then
  echo "Keeping mount: ${mount}"
fi

echo "Take ${take}, counts: ${counts}"

# This is optional, and removes the temporary file.
rm ${PARSED}
