#!/usr/bin/env bash
#
# Packages this project's scripts into a downloadable tarball
set -eu
source utils.sh

declare -r DEST=/tmp/common-utils
declare -r BASE=$(abspath $(dirname $0))

${BASE}/make-tag
declare VERSION=$(git tag | tail -1)
if [[ -z ${VERSION} ]]
then
  echo "Found no applicable tags to use as VERSION"
  exit 1
fi
msg "Bulding Common Utilities release ${VERSION}"


mkdir -p ${DEST}
for f in build parse-args runtests utils; do
  cp $f.* ${DEST}/$f
  chmod +x $DEST/$f
done
cp commons.cmake $DEST/

# Generate HTML instructions.
pandoc README.md -t html -o ${DEST}/README.html

mkdir -p rel
tar cvf rel/common-utils-$VERSION.tar.gz -C /tmp common-utils
rm -rf $DEST
success "Release tarball in rel/common-utils-$VERSION.tar.gz"
