# Upon pushing to the release branch a new tag will be created
# in preparation for the release; then a new tarball will be created;
# and finally a Release will be generated.
#
# Copyright (c) 2022 AlertAvert.com.  All rights reserved.
# Author: Marco Massenzio (marco@alertavert.com)
#
name: Release

on:
  push:
    branches:
      - release
env:
  AUTHOR: ${{ github.event.pusher.name }}
  EMAIL: ${{ github.event.pusher.email }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create release tag
        run: |
          git config user.name "$AUTHOR"
          git config user.email "<$EMAIL>"
          TAG=$(make version)
          git tag -a $TAG -m "Release $TAG"
          git push --tags
          echo TAG=${TAG} >> $GITHUB_ENV

      - name: Build tarball
        run: |
          sudo apt install -y pandoc
          make package

      - uses: ncipollo/release-action@v1.10.0
        with:
          tag: ${{ env.TAG }}
          generateReleaseNotes: true
          artifacts: dist/common-utils-${{ env.TAG }}.tar.gz
